default_install_hook_types = ["pre-commit", "commit-msg", "pre-push"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer", exclude_types = ["rust"] },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/ComPWA/taplo-pre-commit"
rev = "v0.9.3"
hooks = [
  { id = "taplo-format", args = ["--option", "array_auto_collapse=false"] },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.6.0"
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch", stages = ["pre-push"] },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
types = ["file", "rust"]
pass_filenames = true
entry = "cargo fmt --all --"

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
language = "system"
types = ["file", "rust"]
pass_filenames = false
entry = "cargo clippy --all-targets --all-features -- -Dclippy::all"
